repositories {
    mavenCentral()
    google() // Needed for androidx
    maven { url = 'https://maven.brott.dev/' }
    maven { url = 'https://mymaven.bylazar.com/releases' }
    maven { url = 'https://maven.pedropathing.com/' }
    maven { url = 'https://repo.dairy.foundation/releases/' }
    maven { url = 'https://maven.frozenmilk.dev/releases' }
    maven { url = 'https://jitpack.io' }
}

dependencies {
    implementation 'org.firstinspires.ftc:Inspection:11.1.0'
    implementation 'org.firstinspires.ftc:Blocks:11.1.0'
    // noinspection Aligned16KB
    implementation 'org.firstinspires.ftc:RobotCore:11.1.0'
    implementation 'org.firstinspires.ftc:RobotServer:11.1.0'
    implementation 'org.firstinspires.ftc:OnBotJava:11.1.0'
    implementation 'org.firstinspires.ftc:Hardware:11.1.0'
    implementation 'org.firstinspires.ftc:FtcCommon:11.1.0'
    implementation 'org.firstinspires.ftc:Vision:11.1.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.acmerobotics.dashboard:dashboard:0.5.1'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
    implementation 'com.bylazar:fullpanels:1.0.12'

    // Pedro Pathing v3
    implementation 'com.pedropathing:revhub:3.0.0'
    implementation 'com.pedropathing:tuning:1.0.0'
    implementation 'com.pedropathing:core:3.0.0'
    implementation 'com.pedropathing.ivy:core:1.1.1'
    implementation 'com.pedropathing.ivy:pedro:1.1.1'
}
